ci:
  autofix_prs: true
  autoupdate_schedule: quarterly

default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
        name: End-of-file fixer
      - id: trailing-whitespace
        name: Remove trailing whitespaces

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.0
    hooks:
      - id: ruff-check
        name: Ruff lint
        args: [--fix]
      - id: ruff-format
        name: Ruff format
