version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.13"

python:
  install:
    - method: uv
      command: pip
      path: .
      extras:
        - doc
