name: tsl
channels:
  - pytorch
  - pyg
  - nvidia                    # remove for cpu installation
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.0.0
  - pytorch-cuda>=11.7         # remove for cpu installation
  - pyg
  - pytorch-scatter
  - pytorch-sparse
  - lightning
  - pip
  - pip:
      - einops
      - hydra-core
      - numpy>1.20.3
      - omegaconf
      - pandas>=1.4
      - PyYAML
      - scikit-learn
      - scipy
      - tables
      - torchmetrics>=0.7
      - tqdm
