name: tsl
channels:
  - pytorch
  - pyg
  - nvidia                    # remove for cpu installation
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.2
  - pytorch-cuda>=11.7         # remove for cpu installation
  - pyg>=2.4
  - pytorch-scatter
  - pytorch-sparse
  - lightning
  - pip
  - pip:
      - einops
      - hydra-core>=1.3,<1.4
      - numpy>=1.26,<3
      - omegaconf>=2.3,<2.4
      - pandas>=2,<3
      - PyYAML
      - scikit-learn
      - scipy
      - tables
      - torchmetrics>=1,<2
      - tqdm
